/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountOut model module.
 * @module model/AccountOut
 * @version 1.0.0
 */
class AccountOut {
    /**
     * Constructs a new <code>AccountOut</code>.
     * @alias module:model/AccountOut
     * @param balance {Number} 
     */
    constructor(balance) { 
        
        AccountOut.initialize(this, balance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, balance) { 
        obj['balance'] = balance;
    }

    /**
     * Constructs a <code>AccountOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountOut} obj Optional instance to populate.
     * @return {module:model/AccountOut} The populated <code>AccountOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('is_unlimited')) {
                obj['is_unlimited'] = ApiClient.convertToType(data['is_unlimited'], 'Boolean');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
AccountOut.prototype['id'] = undefined;

/**
 * @member {Boolean} is_unlimited
 * @default false
 */
AccountOut.prototype['is_unlimited'] = false;

/**
 * @member {Number} balance
 */
AccountOut.prototype['balance'] = undefined;






export default AccountOut;

