/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountAmountSchema model module.
 * @module model/AccountAmountSchema
 * @version 1.0.0
 */
class AccountAmountSchema {
    /**
     * Constructs a new <code>AccountAmountSchema</code>.
     * @alias module:model/AccountAmountSchema
     * @param accountId {Number} 
     * @param amount {Number} 
     */
    constructor(accountId, amount) { 
        
        AccountAmountSchema.initialize(this, accountId, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountId, amount) { 
        obj['account_id'] = accountId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>AccountAmountSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountAmountSchema} obj Optional instance to populate.
     * @return {module:model/AccountAmountSchema} The populated <code>AccountAmountSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountAmountSchema();

            if (data.hasOwnProperty('account_id')) {
                obj['account_id'] = ApiClient.convertToType(data['account_id'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} account_id
 */
AccountAmountSchema.prototype['account_id'] = undefined;

/**
 * @member {Number} amount
 */
AccountAmountSchema.prototype['amount'] = undefined;






export default AccountAmountSchema;

