/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateUserSchema model module.
 * @module model/CreateUserSchema
 * @version 1.0.0
 */
class CreateUserSchema {
    /**
     * Constructs a new <code>CreateUserSchema</code>.
     * @alias module:model/CreateUserSchema
     * @param username {String} Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @param password {String} 
     * @param teamId {Number} 
     */
    constructor(username, password, teamId) { 
        
        CreateUserSchema.initialize(this, username, password, teamId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, teamId) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['team_id'] = teamId;
    }

    /**
     * Constructs a <code>CreateUserSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserSchema} obj Optional instance to populate.
     * @return {module:model/CreateUserSchema} The populated <code>CreateUserSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserSchema();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @member {String} username
 */
CreateUserSchema.prototype['username'] = undefined;

/**
 * @member {String} first_name
 */
CreateUserSchema.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
CreateUserSchema.prototype['last_name'] = undefined;

/**
 * @member {String} email
 */
CreateUserSchema.prototype['email'] = undefined;

/**
 * @member {String} role
 * @default 'PLAYER'
 */
CreateUserSchema.prototype['role'] = 'PLAYER';

/**
 * @member {String} password
 */
CreateUserSchema.prototype['password'] = undefined;

/**
 * @member {Number} team_id
 */
CreateUserSchema.prototype['team_id'] = undefined;






export default CreateUserSchema;

