/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTeamSchema model module.
 * @module model/CreateTeamSchema
 * @version 1.0.0
 */
class CreateTeamSchema {
    /**
     * Constructs a new <code>CreateTeamSchema</code>.
     * @alias module:model/CreateTeamSchema
     * @param name {String} 
     * @param balance {Number} 
     */
    constructor(name, balance) { 
        
        CreateTeamSchema.initialize(this, name, balance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, balance) { 
        obj['name'] = name;
        obj['balance'] = balance;
    }

    /**
     * Constructs a <code>CreateTeamSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTeamSchema} obj Optional instance to populate.
     * @return {module:model/CreateTeamSchema} The populated <code>CreateTeamSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTeamSchema();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CreateTeamSchema.prototype['name'] = undefined;

/**
 * @member {Number} balance
 */
CreateTeamSchema.prototype['balance'] = undefined;






export default CreateTeamSchema;

