/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Detail model module.
 * @module model/Detail
 * @version 1.0.0
 */
class Detail {
    /**
     * Constructs a new <code>Detail</code>.
     * @alias module:model/Detail
     * @param detail {module:model/AnyOfstringarrayarrayobject} 
     */
    constructor(detail) { 
        
        Detail.initialize(this, detail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, detail) { 
        obj['detail'] = detail;
    }

    /**
     * Constructs a <code>Detail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Detail} obj Optional instance to populate.
     * @return {module:model/Detail} The populated <code>Detail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Detail();

            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], AnyOfstringarrayarrayobject);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AnyOfstringarrayarrayobject} detail
 */
Detail.prototype['detail'] = undefined;






export default Detail;

