/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlayerTeamSchema model module.
 * @module model/PlayerTeamSchema
 * @version 1.0.0
 */
class PlayerTeamSchema {
    /**
     * Constructs a new <code>PlayerTeamSchema</code>.
     * @alias module:model/PlayerTeamSchema
     * @param playerId {Number} 
     * @param teamId {Number} 
     */
    constructor(playerId, teamId) { 
        
        PlayerTeamSchema.initialize(this, playerId, teamId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, teamId) { 
        obj['player_id'] = playerId;
        obj['team_id'] = teamId;
    }

    /**
     * Constructs a <code>PlayerTeamSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlayerTeamSchema} obj Optional instance to populate.
     * @return {module:model/PlayerTeamSchema} The populated <code>PlayerTeamSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayerTeamSchema();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'Number');
            }
            if (data.hasOwnProperty('team_id')) {
                obj['team_id'] = ApiClient.convertToType(data['team_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} player_id
 */
PlayerTeamSchema.prototype['player_id'] = undefined;

/**
 * @member {Number} team_id
 */
PlayerTeamSchema.prototype['team_id'] = undefined;






export default PlayerTeamSchema;

