/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductKitIn model module.
 * @module model/ProductKitIn
 * @version 1.0.0
 */
class ProductKitIn {
    /**
     * Constructs a new <code>ProductKitIn</code>.
     * @alias module:model/ProductKitIn
     * @param count {Number} 
     * @param time {Number} 
     * @param productId {Number} 
     */
    constructor(count, time, productId) { 
        
        ProductKitIn.initialize(this, count, time, productId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, time, productId) { 
        obj['count'] = count;
        obj['time'] = time;
        obj['product_id'] = productId;
    }

    /**
     * Constructs a <code>ProductKitIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductKitIn} obj Optional instance to populate.
     * @return {module:model/ProductKitIn} The populated <code>ProductKitIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductKitIn();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
ProductKitIn.prototype['count'] = undefined;

/**
 * @member {Number} time
 */
ProductKitIn.prototype['time'] = undefined;

/**
 * @member {Number} product_id
 */
ProductKitIn.prototype['product_id'] = undefined;






export default ProductKitIn;

