/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductIn model module.
 * @module model/ProductIn
 * @version 1.0.0
 */
class ProductIn {
    /**
     * Constructs a new <code>ProductIn</code>.
     * @alias module:model/ProductIn
     * @param name {String} 
     */
    constructor(name) { 
        
        ProductIn.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ProductIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductIn} obj Optional instance to populate.
     * @return {module:model/ProductIn} The populated <code>ProductIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductIn();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ProductIn.prototype['name'] = undefined;






export default ProductIn;

