/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductKitOut model module.
 * @module model/ProductKitOut
 * @version 1.0.0
 */
class ProductKitOut {
    /**
     * Constructs a new <code>ProductKitOut</code>.
     * @alias module:model/ProductKitOut
     * @param product {Number} 
     * @param count {Number} 
     * @param time {Number} 
     */
    constructor(product, count, time) { 
        
        ProductKitOut.initialize(this, product, count, time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, product, count, time) { 
        obj['product'] = product;
        obj['count'] = count;
        obj['time'] = time;
    }

    /**
     * Constructs a <code>ProductKitOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductKitOut} obj Optional instance to populate.
     * @return {module:model/ProductKitOut} The populated <code>ProductKitOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductKitOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ProductKitOut.prototype['id'] = undefined;

/**
 * @member {Number} product
 */
ProductKitOut.prototype['product'] = undefined;

/**
 * @member {Number} count
 */
ProductKitOut.prototype['count'] = undefined;

/**
 * @member {Number} time
 */
ProductKitOut.prototype['time'] = undefined;






export default ProductKitOut;

