/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurchaseOfferOut model module.
 * @module model/PurchaseOfferOut
 * @version 1.0.0
 */
class PurchaseOfferOut {
    /**
     * Constructs a new <code>PurchaseOfferOut</code>.
     * @alias module:model/PurchaseOfferOut
     * @param trader {Number} 
     * @param price {Number} 
     * @param timestamp {Date} 
     * @param product {Number} 
     * @param count {Number} 
     */
    constructor(trader, price, timestamp, product, count) { 
        
        PurchaseOfferOut.initialize(this, trader, price, timestamp, product, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, trader, price, timestamp, product, count) { 
        obj['trader'] = trader;
        obj['price'] = price;
        obj['timestamp'] = timestamp;
        obj['product'] = product;
        obj['count'] = count;
    }

    /**
     * Constructs a <code>PurchaseOfferOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseOfferOut} obj Optional instance to populate.
     * @return {module:model/PurchaseOfferOut} The populated <code>PurchaseOfferOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseOfferOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('trader')) {
                obj['trader'] = ApiClient.convertToType(data['trader'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PurchaseOfferOut.prototype['id'] = undefined;

/**
 * @member {Number} trader
 */
PurchaseOfferOut.prototype['trader'] = undefined;

/**
 * @member {Number} price
 */
PurchaseOfferOut.prototype['price'] = undefined;

/**
 * @member {Date} timestamp
 */
PurchaseOfferOut.prototype['timestamp'] = undefined;

/**
 * @member {String} state
 * @default 'Active'
 */
PurchaseOfferOut.prototype['state'] = 'Active';

/**
 * @member {Number} product
 */
PurchaseOfferOut.prototype['product'] = undefined;

/**
 * @member {Number} count
 */
PurchaseOfferOut.prototype['count'] = undefined;






export default PurchaseOfferOut;

