/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurchaseDoneOut model module.
 * @module model/PurchaseDoneOut
 * @version 1.0.0
 */
class PurchaseDoneOut {
    /**
     * Constructs a new <code>PurchaseDoneOut</code>.
     * @alias module:model/PurchaseDoneOut
     * @param offer {Number} 
     * @param transaction {Number} 
     */
    constructor(offer, transaction) { 
        
        PurchaseDoneOut.initialize(this, offer, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, offer, transaction) { 
        obj['offer'] = offer;
        obj['transaction'] = transaction;
    }

    /**
     * Constructs a <code>PurchaseDoneOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseDoneOut} obj Optional instance to populate.
     * @return {module:model/PurchaseDoneOut} The populated <code>PurchaseDoneOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseDoneOut();

            if (data.hasOwnProperty('offer')) {
                obj['offer'] = ApiClient.convertToType(data['offer'], 'Number');
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = ApiClient.convertToType(data['transaction'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offer
 */
PurchaseDoneOut.prototype['offer'] = undefined;

/**
 * @member {Number} transaction
 */
PurchaseDoneOut.prototype['transaction'] = undefined;






export default PurchaseDoneOut;

