/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurchaseOfferPlace model module.
 * @module model/PurchaseOfferPlace
 * @version 1.0.0
 */
class PurchaseOfferPlace {
    /**
     * Constructs a new <code>PurchaseOfferPlace</code>.
     * @alias module:model/PurchaseOfferPlace
     * @param price {Number} 
     * @param count {Number} 
     * @param productId {Number} 
     */
    constructor(price, count, productId) { 
        
        PurchaseOfferPlace.initialize(this, price, count, productId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, price, count, productId) { 
        obj['price'] = price;
        obj['count'] = count;
        obj['product_id'] = productId;
    }

    /**
     * Constructs a <code>PurchaseOfferPlace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseOfferPlace} obj Optional instance to populate.
     * @return {module:model/PurchaseOfferPlace} The populated <code>PurchaseOfferPlace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseOfferPlace();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} price
 */
PurchaseOfferPlace.prototype['price'] = undefined;

/**
 * @member {Number} count
 */
PurchaseOfferPlace.prototype['count'] = undefined;

/**
 * @member {Number} product_id
 */
PurchaseOfferPlace.prototype['product_id'] = undefined;






export default PurchaseOfferPlace;

