/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SaleOfferOut model module.
 * @module model/SaleOfferOut
 * @version 1.0.0
 */
class SaleOfferOut {
    /**
     * Constructs a new <code>SaleOfferOut</code>.
     * @alias module:model/SaleOfferOut
     * @param trader {Number} 
     * @param price {Number} 
     * @param timestamp {Date} 
     * @param productKit {Number} 
     */
    constructor(trader, price, timestamp, productKit) { 
        
        SaleOfferOut.initialize(this, trader, price, timestamp, productKit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, trader, price, timestamp, productKit) { 
        obj['trader'] = trader;
        obj['price'] = price;
        obj['timestamp'] = timestamp;
        obj['product_kit'] = productKit;
    }

    /**
     * Constructs a <code>SaleOfferOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SaleOfferOut} obj Optional instance to populate.
     * @return {module:model/SaleOfferOut} The populated <code>SaleOfferOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaleOfferOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('trader')) {
                obj['trader'] = ApiClient.convertToType(data['trader'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('product_kit')) {
                obj['product_kit'] = ApiClient.convertToType(data['product_kit'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SaleOfferOut.prototype['id'] = undefined;

/**
 * @member {Number} trader
 */
SaleOfferOut.prototype['trader'] = undefined;

/**
 * @member {Number} price
 */
SaleOfferOut.prototype['price'] = undefined;

/**
 * @member {Date} timestamp
 */
SaleOfferOut.prototype['timestamp'] = undefined;

/**
 * @member {String} state
 * @default 'Active'
 */
SaleOfferOut.prototype['state'] = 'Active';

/**
 * @member {Number} product_kit
 */
SaleOfferOut.prototype['product_kit'] = undefined;






export default SaleOfferOut;

