/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SaleOfferPlace model module.
 * @module model/SaleOfferPlace
 * @version 1.0.0
 */
class SaleOfferPlace {
    /**
     * Constructs a new <code>SaleOfferPlace</code>.
     * @alias module:model/SaleOfferPlace
     * @param price {Number} 
     * @param productKitId {Number} 
     */
    constructor(price, productKitId) { 
        
        SaleOfferPlace.initialize(this, price, productKitId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, price, productKitId) { 
        obj['price'] = price;
        obj['product_kit_id'] = productKitId;
    }

    /**
     * Constructs a <code>SaleOfferPlace</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SaleOfferPlace} obj Optional instance to populate.
     * @return {module:model/SaleOfferPlace} The populated <code>SaleOfferPlace</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaleOfferPlace();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('product_kit_id')) {
                obj['product_kit_id'] = ApiClient.convertToType(data['product_kit_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} price
 */
SaleOfferPlace.prototype['price'] = undefined;

/**
 * @member {Number} product_kit_id
 */
SaleOfferPlace.prototype['product_kit_id'] = undefined;






export default SaleOfferPlace;

