/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductKitOut from './ProductKitOut';

/**
 * The StoreProductKitOut model module.
 * @module model/StoreProductKitOut
 * @version 1.0.0
 */
class StoreProductKitOut {
    /**
     * Constructs a new <code>StoreProductKitOut</code>.
     * @alias module:model/StoreProductKitOut
     * @param productKit {module:model/ProductKitOut} 
     * @param count {Number} 
     */
    constructor(productKit, count) { 
        
        StoreProductKitOut.initialize(this, productKit, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productKit, count) { 
        obj['product_kit'] = productKit;
        obj['count'] = count;
    }

    /**
     * Constructs a <code>StoreProductKitOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreProductKitOut} obj Optional instance to populate.
     * @return {module:model/StoreProductKitOut} The populated <code>StoreProductKitOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreProductKitOut();

            if (data.hasOwnProperty('product_kit')) {
                obj['product_kit'] = ProductKitOut.constructFromObject(data['product_kit']);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProductKitOut} product_kit
 */
StoreProductKitOut.prototype['product_kit'] = undefined;

/**
 * @member {Number} count
 */
StoreProductKitOut.prototype['count'] = undefined;






export default StoreProductKitOut;

