/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductOut from './ProductOut';

/**
 * The StoreProductOut model module.
 * @module model/StoreProductOut
 * @version 1.0.0
 */
class StoreProductOut {
    /**
     * Constructs a new <code>StoreProductOut</code>.
     * @alias module:model/StoreProductOut
     * @param product {module:model/ProductOut} 
     * @param count {Number} 
     */
    constructor(product, count) { 
        
        StoreProductOut.initialize(this, product, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, product, count) { 
        obj['product'] = product;
        obj['count'] = count;
    }

    /**
     * Constructs a <code>StoreProductOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreProductOut} obj Optional instance to populate.
     * @return {module:model/StoreProductOut} The populated <code>StoreProductOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreProductOut();

            if (data.hasOwnProperty('product')) {
                obj['product'] = ProductOut.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProductOut} product
 */
StoreProductOut.prototype['product'] = undefined;

/**
 * @member {Number} count
 */
StoreProductOut.prototype['count'] = undefined;






export default StoreProductOut;

