/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamOutSchema model module.
 * @module model/TeamOutSchema
 * @version 1.0.0
 */
class TeamOutSchema {
    /**
     * Constructs a new <code>TeamOutSchema</code>.
     * @alias module:model/TeamOutSchema
     * @param name {String} 
     * @param account {Number} 
     */
    constructor(name, account) { 
        
        TeamOutSchema.initialize(this, name, account);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, account) { 
        obj['name'] = name;
        obj['account'] = account;
    }

    /**
     * Constructs a <code>TeamOutSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamOutSchema} obj Optional instance to populate.
     * @return {module:model/TeamOutSchema} The populated <code>TeamOutSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamOutSchema();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
TeamOutSchema.prototype['id'] = undefined;

/**
 * @member {String} name
 */
TeamOutSchema.prototype['name'] = undefined;

/**
 * @member {Number} account
 */
TeamOutSchema.prototype['account'] = undefined;






export default TeamOutSchema;

