/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenObtainPairOutput model module.
 * @module model/TokenObtainPairOutput
 * @version 1.0.0
 */
class TokenObtainPairOutput {
    /**
     * Constructs a new <code>TokenObtainPairOutput</code>.
     * @alias module:model/TokenObtainPairOutput
     * @param refresh {String} 
     * @param access {String} 
     * @param username {String} 
     */
    constructor(refresh, access, username) { 
        
        TokenObtainPairOutput.initialize(this, refresh, access, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refresh, access, username) { 
        obj['refresh'] = refresh;
        obj['access'] = access;
        obj['username'] = username;
    }

    /**
     * Constructs a <code>TokenObtainPairOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenObtainPairOutput} obj Optional instance to populate.
     * @return {module:model/TokenObtainPairOutput} The populated <code>TokenObtainPairOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenObtainPairOutput();

            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refresh
 */
TokenObtainPairOutput.prototype['refresh'] = undefined;

/**
 * @member {String} access
 */
TokenObtainPairOutput.prototype['access'] = undefined;

/**
 * @member {String} username
 */
TokenObtainPairOutput.prototype['username'] = undefined;






export default TokenObtainPairOutput;

