/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenRefreshSchema model module.
 * @module model/TokenRefreshSchema
 * @version 1.0.0
 */
class TokenRefreshSchema {
    /**
     * Constructs a new <code>TokenRefreshSchema</code>.
     * @alias module:model/TokenRefreshSchema
     * @param refresh {String} 
     */
    constructor(refresh) { 
        
        TokenRefreshSchema.initialize(this, refresh);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refresh) { 
        obj['refresh'] = refresh;
    }

    /**
     * Constructs a <code>TokenRefreshSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenRefreshSchema} obj Optional instance to populate.
     * @return {module:model/TokenRefreshSchema} The populated <code>TokenRefreshSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenRefreshSchema();

            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refresh
 */
TokenRefreshSchema.prototype['refresh'] = undefined;






export default TokenRefreshSchema;

