/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenRefreshSerializer model module.
 * @module model/TokenRefreshSerializer
 * @version 1.0.0
 */
class TokenRefreshSerializer {
    /**
     * Constructs a new <code>TokenRefreshSerializer</code>.
     * @alias module:model/TokenRefreshSerializer
     * @param refresh {String} 
     */
    constructor(refresh) { 
        
        TokenRefreshSerializer.initialize(this, refresh);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refresh) { 
        obj['refresh'] = refresh;
    }

    /**
     * Constructs a <code>TokenRefreshSerializer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenRefreshSerializer} obj Optional instance to populate.
     * @return {module:model/TokenRefreshSerializer} The populated <code>TokenRefreshSerializer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenRefreshSerializer();

            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refresh
 */
TokenRefreshSerializer.prototype['refresh'] = undefined;

/**
 * @member {String} access
 */
TokenRefreshSerializer.prototype['access'] = undefined;






export default TokenRefreshSerializer;

