/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionOut model module.
 * @module model/TransactionOut
 * @version 1.0.0
 */
class TransactionOut {
    /**
     * Constructs a new <code>TransactionOut</code>.
     * @alias module:model/TransactionOut
     * @param amount {Number} 
     * @param timestamp {Date} 
     */
    constructor(amount, timestamp) { 
        
        TransactionOut.initialize(this, amount, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, timestamp) { 
        obj['amount'] = amount;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>TransactionOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionOut} obj Optional instance to populate.
     * @return {module:model/TransactionOut} The populated <code>TransactionOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionOut();

            if (data.hasOwnProperty('from_account')) {
                obj['from_account'] = ApiClient.convertToType(data['from_account'], 'Number');
            }
            if (data.hasOwnProperty('to_account')) {
                obj['to_account'] = ApiClient.convertToType(data['to_account'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} from_account
 */
TransactionOut.prototype['from_account'] = undefined;

/**
 * @member {Number} to_account
 */
TransactionOut.prototype['to_account'] = undefined;

/**
 * @member {Number} amount
 */
TransactionOut.prototype['amount'] = undefined;

/**
 * @member {Date} timestamp
 */
TransactionOut.prototype['timestamp'] = undefined;






export default TransactionOut;

