/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransferSchema model module.
 * @module model/TransferSchema
 * @version 1.0.0
 */
class TransferSchema {
    /**
     * Constructs a new <code>TransferSchema</code>.
     * @alias module:model/TransferSchema
     * @param accountIdFrom {Number} 
     * @param accountIdTo {Number} 
     * @param amount {Number} 
     */
    constructor(accountIdFrom, accountIdTo, amount) { 
        
        TransferSchema.initialize(this, accountIdFrom, accountIdTo, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountIdFrom, accountIdTo, amount) { 
        obj['account_id_from'] = accountIdFrom;
        obj['account_id_to'] = accountIdTo;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>TransferSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransferSchema} obj Optional instance to populate.
     * @return {module:model/TransferSchema} The populated <code>TransferSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransferSchema();

            if (data.hasOwnProperty('account_id_from')) {
                obj['account_id_from'] = ApiClient.convertToType(data['account_id_from'], 'Number');
            }
            if (data.hasOwnProperty('account_id_to')) {
                obj['account_id_to'] = ApiClient.convertToType(data['account_id_to'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} account_id_from
 */
TransferSchema.prototype['account_id_from'] = undefined;

/**
 * @member {Number} account_id_to
 */
TransferSchema.prototype['account_id_to'] = undefined;

/**
 * @member {Number} amount
 */
TransferSchema.prototype['amount'] = undefined;






export default TransferSchema;

