/**
 * NinjaExtraAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserOut model module.
 * @module model/UserOut
 * @version 1.0.0
 */
class UserOut {
    /**
     * Constructs a new <code>UserOut</code>.
     * @alias module:model/UserOut
     * @param username {String} Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    constructor(username) { 
        
        UserOut.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserOut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserOut} obj Optional instance to populate.
     * @return {module:model/UserOut} The populated <code>UserOut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserOut();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('last_login')) {
                obj['last_login'] = ApiClient.convertToType(data['last_login'], 'Date');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('date_joined')) {
                obj['date_joined'] = ApiClient.convertToType(data['date_joined'], 'Date');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('team')) {
                obj['team'] = ApiClient.convertToType(data['team'], 'Number');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
            if (data.hasOwnProperty('is_superuser')) {
                obj['is_superuser'] = ApiClient.convertToType(data['is_superuser'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
UserOut.prototype['id'] = undefined;

/**
 * @member {Date} last_login
 */
UserOut.prototype['last_login'] = undefined;

/**
 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @member {String} username
 */
UserOut.prototype['username'] = undefined;

/**
 * @member {String} first_name
 */
UserOut.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
UserOut.prototype['last_name'] = undefined;

/**
 * @member {String} email
 */
UserOut.prototype['email'] = undefined;

/**
 * @member {Date} date_joined
 */
UserOut.prototype['date_joined'] = undefined;

/**
 * @member {String} role
 * @default 'PLAYER'
 */
UserOut.prototype['role'] = 'PLAYER';

/**
 * @member {Number} team
 */
UserOut.prototype['team'] = undefined;

/**
 * @member {Number} account
 */
UserOut.prototype['account'] = undefined;

/**
 * Designates that this user has all permissions without explicitly assigning them.
 * @member {Boolean} is_superuser
 * @default false
 */
UserOut.prototype['is_superuser'] = false;






export default UserOut;

